package pojos;
// Generated Jul 16, 2020 9:36:04 AM by Hibernate Tools 4.3.1

/**
 * Admins generated by hbm2java
 */
public class Admins implements java.io.Serializable {

    private Integer adminId;
    private String fullName;
    private String username;
    private String pass;
    private String email;
    private boolean isDeleted;

    public Admins() {
        this.isDeleted = false;
    }

    public Admins(String fullName, String username, String pass, String email, boolean isDeleted) {
        this();
        this.fullName = fullName;
        this.username = username;
        this.pass = pass;
        this.email = email;
        this.isDeleted = isDeleted;
    }

    public Integer getAdminId() {
        return this.adminId;
    }

    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPass() {
        return this.pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

}
