package pojos;
// Generated Jul 16, 2020 9:36:04 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conferences generated by hbm2java
 */
public class Conferences implements java.io.Serializable {

    private Integer conferenceId;
    private Places places;
    private String conferenceName;
    private String briefDescription;
    private String detailedDescription;
    private String imageLink;
    private Date organizedTime;
    private int registeredAttendees;
    private boolean isDeleted;
    private Set registeredUserses = new HashSet(0);

    public Conferences() {
        this.isDeleted = false;
        this.imageLink = "image.jpg";
    }

    public Conferences(Places places, String conferenceName, String briefDescription, String detailedDescription, String imageLink, Date organizedTime, int registeredAttendees, boolean isDeleted) {
        this();
        this.places = places;
        this.conferenceName = conferenceName;
        this.briefDescription = briefDescription;
        this.detailedDescription = detailedDescription;
        this.imageLink = imageLink;
        this.organizedTime = organizedTime;
        this.registeredAttendees = registeredAttendees;
        this.isDeleted = isDeleted;
    }

    public Conferences(Places places, String conferenceName, String briefDescription, String detailedDescription, String imageLink, Date organizedTime, int registeredAttendees, boolean isDeleted, Set registeredUserses) {
        this();
        this.places = places;
        this.conferenceName = conferenceName;
        this.briefDescription = briefDescription;
        this.detailedDescription = detailedDescription;
        this.imageLink = imageLink;
        this.organizedTime = organizedTime;
        this.registeredAttendees = registeredAttendees;
        this.isDeleted = isDeleted;
        this.registeredUserses = registeredUserses;
    }

    public Integer getConferenceId() {
        return this.conferenceId;
    }

    public void setConferenceId(Integer conferenceId) {
        this.conferenceId = conferenceId;
    }

    public Places getPlaces() {
        return this.places;
    }

    public void setPlaces(Places places) {
        this.places = places;
    }

    public String getConferenceName() {
        return this.conferenceName;
    }

    public void setConferenceName(String conferenceName) {
        this.conferenceName = conferenceName;
    }

    public String getBriefDescription() {
        return this.briefDescription;
    }

    public void setBriefDescription(String briefDescription) {
        this.briefDescription = briefDescription;
    }

    public String getDetailedDescription() {
        return this.detailedDescription;
    }

    public void setDetailedDescription(String detailedDescription) {
        this.detailedDescription = detailedDescription;
    }

    public String getImageLink() {
        return imageLink;
    }

    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }

    public Date getOrganizedTime() {
        return this.organizedTime;
    }

    public void setOrganizedTime(Date organizedTime) {
        this.organizedTime = organizedTime;
    }

    public int getRegisteredAttendees() {
        return this.registeredAttendees;
    }

    public void setRegisteredAttendees(int registeredAttendees) {
        this.registeredAttendees = registeredAttendees;
    }

    public boolean isIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Set getRegisteredUserses() {
        return this.registeredUserses;
    }

    public void setRegisteredUserses(Set registeredUserses) {
        this.registeredUserses = registeredUserses;
    }

}
