package pojos;
// Generated Jul 16, 2020 9:36:04 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Places generated by hbm2java
 */
public class Places implements java.io.Serializable {

    private Integer placeId;
    private String placeName;
    private String placeAddress;
    private int capacity;
    private boolean isDeleted;
    private Set conferenceses = new HashSet(0);

    public Places() {
        this.isDeleted = false;
    }

    public Places(String placeName, String placeAddress, int capacity, boolean isDeleted) {
        this();
        this.placeName = placeName;
        this.placeAddress = placeAddress;
        this.capacity = capacity;
        this.isDeleted = isDeleted;
    }

    public Places(String placeName, String placeAddress, int capacity, boolean isDeleted, Set conferenceses) {
        this();
        this.placeName = placeName;
        this.placeAddress = placeAddress;
        this.capacity = capacity;
        this.isDeleted = isDeleted;
        this.conferenceses = conferenceses;
    }

    public Integer getPlaceId() {
        return this.placeId;
    }

    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }

    public String getPlaceName() {
        return this.placeName;
    }

    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }

    public String getPlaceAddress() {
        return this.placeAddress;
    }

    public void setPlaceAddress(String placeAddress) {
        this.placeAddress = placeAddress;
    }

    public int getCapacity() {
        return this.capacity;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    public boolean isIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Set getConferenceses() {
        return this.conferenceses;
    }

    public void setConferenceses(Set conferenceses) {
        this.conferenceses = conferenceses;
    }

    @Override
    public String toString() {
        return "Places{" + "placeId=" + placeId + '}';
    }

    
}
