package pojos;
// Generated Jul 16, 2020 9:36:04 AM by Hibernate Tools 4.3.1

/**
 * RegisteredUsers generated by hbm2java
 */
public class RegisteredUsers implements java.io.Serializable {
    
    private RegisteredUsersId id;
    private Conferences conferences;
    private Users users;
    private boolean isAccepted;
    private boolean isDeleted;
    
    public RegisteredUsers() {
        this.isAccepted = false;
        this.isDeleted = false;
    }
    
    public RegisteredUsers(RegisteredUsersId id, Conferences conferences, Users users, boolean isAccepted, boolean isDeleted) {
        this();
        this.id = id;
        this.conferences = conferences;
        this.users = users;
        this.isAccepted = isAccepted;
        this.isDeleted = isDeleted;
    }
    
    public RegisteredUsersId getId() {
        return this.id;
    }
    
    public void setId(RegisteredUsersId id) {
        this.id = id;
    }

    public Conferences getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Conferences conferences) {
        this.conferences = conferences;
    }

    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    public boolean isIsAccepted() {
        return this.isAccepted;
    }
    
    public void setIsAccepted(boolean isAccepted) {
        this.isAccepted = isAccepted;
    }

    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    
}
