package pojos;
// Generated Jul 16, 2020 9:36:04 AM by Hibernate Tools 4.3.1

/**
 * RegisteredUsersId generated by hbm2java
 */
public class RegisteredUsersId implements java.io.Serializable {

    private int userId;
    private int conferenceId;

    public RegisteredUsersId() {
    }

    public RegisteredUsersId(int userId, int conferenceId) {
        this.userId = userId;
        this.conferenceId = conferenceId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getConferenceId() {
        return this.conferenceId;
    }

    public void setConferenceId(int conferenceId) {
        this.conferenceId = conferenceId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof RegisteredUsersId)) {
            return false;
        }
        RegisteredUsersId castOther = (RegisteredUsersId) other;

        return (this.getUserId() == castOther.getUserId())
                && (this.getConferenceId() == castOther.getConferenceId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUserId();
        result = 37 * result + this.getConferenceId();
        return result;
    }

}
