package pojos;
// Generated Jul 16, 2020 9:36:04 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private Integer userId;
    private String fullName;
    private String username;
    private String pass;
    private String email;
    private boolean isBlocked;
    private boolean isDeleted;
    private Set registeredUserses = new HashSet(0);

    public Users() {
        this.isBlocked = false;
        this.isDeleted = false;
    }

    public Users(String fullName, String username, String pass, String email, boolean isBlocked, boolean isDeleted) {
        this();
        this.fullName = fullName;
        this.username = username;
        this.pass = pass;
        this.email = email;
        this.isBlocked = isBlocked;
        this.isDeleted = isDeleted;
    }

    public Users(String fullName, String username, String pass, String email, boolean isBlocked, boolean isDeleted, Set registeredUserses) {
        this();
        this.fullName = fullName;
        this.username = username;
        this.pass = pass;
        this.email = email;
        this.isBlocked = isBlocked;
        this.isDeleted = isDeleted;
        this.registeredUserses = registeredUserses;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPass() {
        return this.pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean getIsBlocked() {
        return this.isBlocked;
    }

    public void setIsBlocked(boolean isBlocked) {
        this.isBlocked = isBlocked;
    }

    public boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Set getRegisteredUserses() {
        return this.registeredUserses;
    }

    public void setRegisteredUserses(Set registeredUserses) {
        this.registeredUserses = registeredUserses;
    }

}
